### ISSUE TITLE
Fix the `hello_network` docs about how to use WiFi

### ISSUE THREAD

**Issue by GregMefford** [nerves-project/nerves_examples#106]
It seems that when we added `nerves_init_gadget` to the `hello_network` example, it made things more confusing about how to use WiFi instead of USB gadget Ethernet because now that's handled by `nerves_init_gadget` instead of the actual `hello_network` code.

Go through the process and get it working, then update the `config.exs` and `README.md` to make it more obvious for people to end up in the right place.

**Comment by HangingClowns** [comment]
@GregMefford since I brought this "trouble" please assign to me. I'd like to help where I can.

**Comment by GregMefford** [comment]
Haha we actually love when people report problems or things that could be better/clearer so that we can keep improving.

Please feel free to work on it and reach out/keep asking questions if you have trouble or decide you don’t have time!

**Comment by GregMefford** [comment]
Not sure why the `resolves` thing didn't work automatically, but this was resolved in #110.
