### ISSUE TITLE
Update examples to match Nerves new project generator

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves_examples#167]
There are a few minor updates in the latest new project generator that should be reflected in the examples:

1. The Nerves integration was simplified to remove the bootstrap mix.exs alias and add a line to the the config.exs
2. The vm.args were updated to turn off Erlang's busy wait
3. Various dependency specs in the mix.exs were bumped

**Comment by GregMefford** [comment]
I'll see if I can get these updates done today.

**Comment by GregMefford** [comment]
I got all my stuff updated and ready to go, and then I was confused about what to actually do because it seems that [the `nerves_bootstrap` updates haven't been actually released yet](https://github.com/nerves-project/nerves_bootstrap/pull/166), so this one is blocked until that's released.

**Comment by fhunleth** [comment]
`nerves_bootstrap` hasn't been released, since we've had trouble with the Elixir 1.11 upgrade and Justin is out. 

The `vm.args` and dependency spec bumps are harmless. They don't really do anything since the `vm.args` change can only be noticed if you're really watching CPU usage. The spec bumps to the `mix.exs` don't change what's used since the `mix.lock` already has the new versions. These are more chores than anything else. 

I'm pretty sure that the change for how to pull the `nerves` infrastructure in works with the current bootstrap as well. 

So the summary is that none of these changes depend on `nerves_bootstrap` being released.

**Comment by GregMefford** [comment]
Oh right, I can still work on making the updates - I was just planning on doing it by using the generator to re-generate the project and then check the diff to make sure I didn't miss anything.

I can also just install the generator from that branch and do the same thing without it being published, so I will try that.
