### ISSUE TITLE
Add local database creation and use to hello_phoenix

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves_examples#225]
Currently the `hello_phoenix` app doesn't use a database, and it's getting to be a more common question. It would nice to add it here and have it do something minimal - perhaps hold the value of a counter between reboots or something like that.

For an example that uses `ecto_sqlite3`, see https://github.com/lawik/calendar_gadget.

**Comment by ConnorRigby** [comment]
This was fixed in #226 right?

**Comment by fhunleth** [comment]
Yes, thanks!
