### ISSUE TITLE
Move neopixel example out?

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves_examples#78]
How do people feel about moving the Neopixel example out of this project? It's the one project in here that requires additional hardware beyond a BBB or RPi, and it only runs on one platform. It also seems like the example would be easier to maintain if it were included in the `nerves_neopixel` project.

**Comment by ConnorRigby** [comment]
I was thinking this also. I do feel like `neopixel` is one of the first projects people try out with Nerves tho.

Maybe it would be a decent idea to have a `AwesomeNerves` repo on the ole GitHubs somewhere for this kind of thing.

**Comment by fhunleth** [comment]
Fwiw, there are a few places that exist already for Nerves libraries and examples including our website: https://nerves-project.org/libraries/.

**Comment by GregMefford** [comment]
I'm fine with removing the `neopixel` example. It's a pain to maintain it and it doesn't make sense for it to be a burden on the Nerves team itself. I'll probably just make an example repo and we can link to it from the website and from the `nerves_neopixel` docs.
