### ISSUE TITLE
hello_network fresh build console stuck on the error

### ISSUE THREAD

**Issue by ychaudhari7** [nerves-project/nerves_examples#94]
> elixir version -  Elixir 1.6.6 (compiled with OTP 19)

`|nerves_bootstrap|` Environment Package List

  Pkg:         nerves_system_br
  Vsn:         1.4.1
  Type:        system_platform
  BuildRunner: nil

  Pkg:         nerves_system_rpi0
  Vsn:         1.3.0
  Type:        system
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

  Pkg:         nerves_toolchain_armv6_rpi_linux_gnueabi
  Vsn:         1.1.0
  Type:        toolchain
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

  Pkg:         nerves_toolchain_ctng
  Vsn:         1.5.0
  Type:        toolchain_platform
  BuildRunner: nil

|nerves_bootstrap| Loadpaths Start

Nerves environment
  MIX_TARGET:   rpi0
  MIX_ENV:      dev

|nerves_bootstrap| Environment Variable List
  target:     rpi0
  toolchain:  /home/ganesh/.nerves/artifacts/nerves_toolchain_armv6_rpi_linux_gnueabi-linux_x86_64-1.1.0
  system:     /home/ganesh/.nerves/artifacts/nerves_system_rpi0-portable-1.3.0
  app:        /home/ganesh/notes/nerves_examples/hello_network

|nerves_bootstrap| Loadpaths End`

After burning new hello_network firmware on rpi0 console is stuck here
> IPv6 ADDRCONF(NETDEV_CHANGE) wlan0: link becomes ready

And Keyboard doesnt works

**Comment by fhunleth** [comment]
We'll need some more information to be able to help you. Could you look at our issue template at https://github.com/nerves-project/nerves/blob/master/ISSUE_TEMPLATE.md and let us know more about your setup?
